# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='usersavedevent',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserSavedEvent',
        ),
    ]
